<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>sqlalchemy on Some Title</title>
    <link>https://japan2018.github.io/tags/sqlalchemy/</link>
    <description>Recent content in sqlalchemy on Some Title</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Sat, 11 Apr 2020 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://japan2018.github.io/tags/sqlalchemy/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>SQLAlchemy&#43;SQLite3„ÅßOperationalError</title>
      <link>https://japan2018.github.io/sqlalchemy-sqlite3%E3%81%A7operationalerror-fa7f2/</link>
      <pubDate>Sat, 11 Apr 2020 00:00:00 +0000</pubDate>
      
      <guid>https://japan2018.github.io/sqlalchemy-sqlite3%E3%81%A7operationalerror-fa7f2/</guid>
      <description># Thing you want to do   I want to use SQLite3 with SQLAlchemy I want to specify the DB file with an absolute path  Environment Python3.8.1 on alpine linux 3.11 on Docker
What happened I wrote the following code, hoping that a DB file will be created in /var/data
engine = create_engine(&amp;#34;sqlite:///var/data/project.sqlite3&amp;#34;) ... When I ran it, I was angry that the database file could not be opened</description>
    </item>
    
  </channel>
</rss>